// Activity presenter: renders any curriculum activity, handles hints, a second try, supported (scaffold)
// mode, read-aloud with speech recognition, and the hands-on science experiments. Every result is
// recorded in the learner model with timing, attempts, hint use and whether help was needed.
'use strict';

const Present = {
  canListen() { return !!(window.SpeechRecognition || window.webkitSpeechRecognition); },

  // opts: { title, onDone(result), noRecord, frame (short line shown above, e.g. mission context) }
  run(it, opts = {}) {
    this.it = it; this.opts = opts;
    this.r = { correct: false, firstTry: true, attempts: 0, ms: 0, hint: false, audio: false, chosen: null };
    this.t0 = performance.now();
    if (it.scaffold && it.choices && it.choices.length > 3) {
      const keep = [it.answer, ...it.choices.filter(c => c !== it.answer).slice(0, 2)];
      it.choiceHtml = it.choiceHtml ? keep.map(k => it.choiceHtml[it.choices.indexOf(k)]) : undefined;
      it.choices = shuffle(keep);
    }
    if (it.type === 'experiment') return Experiments.run(it);
    this.render();
    const reading = it.subject === 'Reading';
    if (!reading || it.say) Voice.speak(it.say || it.prompt);
    else if (it.scaffold && it.story) this.audio();
  },

  header() {
    const it = this.it, o = this.opts;
    return `<div class="mg-head"><span>${esc(o.title || it.skillName)}</span><span class="muted">${esc(it.subject)}</span></div>
      ${o.frame ? `<div class="frame">${o.frame}</div>` : ''}
      ${it.scaffold ? `<div class="scaffold">💡 Let's do it together: ${esc(it.hint)}</div>` : ''}`;
  },
  tools() {
    return `<div class="tools"><button class="speak" id="pr-say">🔊 Hear it</button>${this.it.scaffold ? '' : '<button class="speak" id="pr-hint">💡 Hint</button>'}</div>`;
  },
  bindTools() {
    const it = this.it;
    $('pr-say').onclick = () => this.audio();
    if ($('pr-hint')) $('pr-hint').onclick = () => { this.r.hint = true; $('pr-hint').outerHTML = `<div class="hintbox">💡 ${esc(it.hint)}</div>`; Voice.speak(it.hint); };
  },
  audio() {
    const it = this.it;
    if (it.subject === 'Reading' && it.readingAudioOptional) this.r.audio = true;   // listening instead of reading = support
    Voice.speak(it.type === 'read' ? it.text : (it.story ? it.story + ' ' : '') + (it.say || it.prompt));
  },

  render() {
    const it = this.it;
    let body = '';
    if (it.story) body += `<div class="mg-story">${it.storyTitle ? `<b>${esc(it.storyTitle)}</b><br>` : ''}${esc(it.story)}</div>`;
    body += `<div class="mg-prompt">${esc(it.prompt)}</div>`;
    if (it.visual) body += `<div class="mg-visual">${esc(it.visual)}</div>`;
    if (it.html) body += `<div class="mg-html">${it.html}</div>`;          // generated by curriculum.js only
    if (it.clock) body += clockSVG(it.clock.h, it.clock.m);
    body += this['body_' + it.type]();
    UI.open(this.header() + body + this.tools() + '<div id="pr-feedback"></div>', { onClose: () => this.cancel() });
    this.bindTools();
    this['bind_' + it.type]();
  },

  // ---------- choice ----------
  body_choice() {
    const it = this.it;
    const one = it.choices.length === 3 && it.choices.some(c => c.length > 14);
    return `<div class="choices ${one ? 'one-col' : ''} ${it.wordChoices ? 'words' : ''}">` + it.choices.map((c, k) => {
      const inner = it.choiceHtml ? it.choiceHtml[k] : it.choiceClock ? clockSVG(+c.split(':')[0], +c.split(':')[1]) : esc(c);
      return `<button class="choice" data-k="${k}">${inner}</button>`;
    }).join('') + '</div>';
  },
  bind_choice() {
    document.querySelectorAll('.choice').forEach(b => b.onclick = () => this.pickChoice(b, this.it.choices[+b.dataset.k]));
  },
  pickChoice(btn, val) {
    const it = this.it;
    if (btn.disabled) return;
    this.r.attempts++; if (this.r.chosen == null) this.r.chosen = val;
    if (val === it.answer) { btn.classList.add('right'); return this.finish(true); }
    btn.classList.add('wrong'); btn.disabled = true; Sound.wrong();
    const retry = this.r.attempts === 1 && it.choices.length >= 3;
    if (retry) { this.r.firstTry = false; this.nudge(); return; }
    document.querySelectorAll('.choice').forEach(c => { if (it.choices[+c.dataset.k] === it.answer) c.classList.add('right'); c.disabled = true; });
    this.finish(false);
  },
  nudge() {
    $('pr-feedback').innerHTML = `<p class="affirm small">Good try! Try again 💪 <span class="muted">${esc(this.it.hint)}</span></p>`;
    Voice.speak('Good try! Try again. ' + this.it.hint);
    this.r.hint = true;
  },

  // ---------- count: tap each object, then pick the number ----------
  body_count() {
    const it = this.it;
    return `<div class="countbox">${Array.from({ length: it.n }, (_, i) => `<button class="cobj" data-i="${i}">${it.emoji}</button>`).join('')}</div>
      <div class="muted center">Counted: <b id="pr-cnt">0</b></div>` + this.body_choice();
  },
  bind_count() {
    let n = 0;
    document.querySelectorAll('.cobj').forEach(b => b.onclick = () => {
      if (b.classList.contains('counted')) return;
      n++; b.classList.add('counted'); b.dataset.n = n; $('pr-cnt').textContent = n; Sound.tap(); Voice.speak(String(n));
    });
    this.bind_choice();
  },

  // ---------- order: tap items in the right order ----------
  body_order() {
    const it = this.it;
    return `<div class="order-slots">${it.order.map((_, i) => `<div class="oslot" data-s="${i}"><small>${i + 1}</small></div>`).join('')}</div>
      <div class="order-items">${it.items.map((x, k) => `<button class="oitem" data-k="${k}">${esc(x)}</button>`).join('')}</div>
      <div class="row-btns"><button class="mid-btn" id="pr-undo">⌫ Undo</button><button class="big-btn pink" id="pr-check">Check ✓</button></div>`;
  },
  bind_order() {
    const it = this.it, placed = [];
    const paint = () => {
      document.querySelectorAll('.oslot').forEach((s, i) => { s.innerHTML = `<small>${i + 1}</small>${placed[i] != null ? esc(it.items[placed[i]]) : ''}`; });
      document.querySelectorAll('.oitem').forEach(b => b.classList.toggle('used', placed.includes(+b.dataset.k)));
    };
    document.querySelectorAll('.oitem').forEach(b => b.onclick = () => { const k = +b.dataset.k; if (placed.includes(k) || placed.length >= it.order.length) return; placed.push(k); Sound.tap(); paint(); });
    $('pr-undo').onclick = () => { placed.pop(); paint(); };
    $('pr-check').onclick = () => {
      if (placed.length < it.order.length) { UI.toast('Place them all first!'); return; }
      this.r.attempts++;
      const got = placed.map(k => it.items[k]);
      const ok = got.every((g, i) => g === it.order[i]);
      if (!ok && this.r.attempts === 1) { this.r.firstTry = false; Sound.wrong(); placed.length = 0; paint(); this.nudge(); return; }
      if (!ok) document.querySelectorAll('.oslot').forEach((s, i) => { s.innerHTML = `<small>${i + 1}</small>${esc(it.order[i])}`; s.classList.add('fix'); });
      this.finish(ok);
    };
  },

  // ---------- build: spell with letter tiles ----------
  body_build() {
    const it = this.it;
    return `<div class="answer-slots">${it.word.split('').map(() => '<div class="slot"></div>').join('')}</div>
      <div class="letters">${it.letters.map((l, k) => `<button class="letter" data-k="${k}">${esc(l)}</button>`).join('')}</div>
      <div class="row-btns"><button class="mid-btn" id="pr-undo">⌫ Undo</button></div>`;
  },
  bind_build() {
    const it = this.it, picked = [];
    const paint = () => {
      document.querySelectorAll('.slot').forEach((s, i) => { s.textContent = picked[i] != null ? it.letters[picked[i]] : ''; });
      document.querySelectorAll('.letter').forEach(b => b.classList.toggle('used', picked.includes(+b.dataset.k)));
    };
    document.querySelectorAll('.letter').forEach(b => b.onclick = () => {
      const k = +b.dataset.k; if (picked.includes(k) || picked.length >= it.word.length) return;
      picked.push(k); Sound.tap(); paint();
      if (picked.length === it.word.length) {
        this.r.attempts++;
        const typed = picked.map(p => it.letters[p]).join('');
        if (this.r.chosen == null) this.r.chosen = typed;
        const ok = typed === it.word;
        if (!ok) {
          // was it the right letters in the wrong order, or a wrong vowel?
          const tag = typed.split('').sort().join('') === it.word.split('').sort().join('') ? 'letter_order' : 'vowel';
          it.tags = Object.assign({}, it.tags, { [typed]: tag });
          if (this.r.attempts === 1) { this.r.firstTry = false; Sound.wrong(); setTimeout(() => { picked.length = 0; paint(); }, 600); this.nudge(); return; }
          document.querySelectorAll('.slot').forEach((s, i) => { s.textContent = it.word[i]; s.style.color = '#ff9f43'; });
        }
        this.finish(ok);
      }
    });
    $('pr-undo').onclick = () => { picked.pop(); paint(); };
  },

  // ---------- target: follow a written direction ----------
  body_target() {
    return `<div class="targets">${this.it.cells.map((c, i) => `<button class="tcell" data-i="${i}">${c}</button>`).join('')}</div>`;
  },
  bind_target() {
    const it = this.it;
    document.querySelectorAll('.tcell').forEach(b => b.onclick = () => {
      if (b.disabled) return;
      const i = +b.dataset.i; this.r.attempts++; if (this.r.chosen == null) this.r.chosen = String(i);
      if (i === it.answerIdx) { b.classList.add('right'); return this.finish(true); }
      b.classList.add('wrong'); b.disabled = true; Sound.wrong();
      if (this.r.attempts === 1) { this.r.firstTry = false; this.nudge(); return; }
      document.querySelectorAll('.tcell')[it.answerIdx].classList.add('right');
      this.finish(false);
    });
  },

  // ---------- sort into two groups ----------
  body_sort() {
    const it = this.it;
    return `<div class="sort-items">${it.items.map((x, k) => `<button class="sitem" data-k="${k}">${x[0]}<small>${esc(x[1])}</small></button>`).join('')}</div>
      <div class="bins">${it.bins.map(b => `<button class="bin" data-b="${b[0]}"><b>${esc(b[1])}</b><div class="bin-in" id="bin-${b[0]}"></div></button>`).join('')}</div>`;
  },
  bind_sort() {
    const it = this.it; let sel = null, done = 0, right = 0;
    document.querySelectorAll('.sitem').forEach(b => b.onclick = () => { if (b.disabled) return; document.querySelectorAll('.sitem').forEach(x => x.classList.remove('sel')); b.classList.add('sel'); sel = +b.dataset.k; Sound.tap(); Voice.speak(it.items[sel][1]); });
    document.querySelectorAll('.bin').forEach(b => b.onclick = () => {
      if (sel == null) { UI.toast('Tap a picture first!'); return; }
      const item = it.items[sel], ok = item[2] === b.dataset.b;
      const el = document.querySelector(`.sitem[data-k="${sel}"]`);
      el.disabled = true; el.classList.remove('sel'); el.classList.add(ok ? 'right' : 'wrong');
      $('bin-' + item[2]).insertAdjacentHTML('beforeend', `<span class="${ok ? '' : 'moved'}">${item[0]}</span>`);
      ok ? Sound.right() : Sound.wrong();
      done++; if (ok) right++; sel = null;
      if (done === it.items.length) {
        this.r.attempts = 1; this.r.partial = right / done; this.r.chosen = `${right}/${done}`;
        this.finish(right / done >= 0.8);
      }
    });
  },

  // ---------- read aloud ----------
  body_read() {
    const it = this.it;
    const words = it.text.split(' ');
    return `<div class="read-text">${words.map((w, i) => `<span data-w="${i}">${esc(w)}</span>`).join(' ')}</div>
      <div class="row-btns">${this.canListen() ? '<button class="big-btn pink" id="pr-mic">🎤 Start reading</button>' : ''}
      <button class="mid-btn" id="pr-self">⭐ I read it to my grown-up</button></div><p class="center muted" id="pr-heard"></p>`;
  },
  bind_read() {
    const it = this.it;
    const norm = (s) => s.toLowerCase().replace(/[^a-z' ]/g, ' ').split(/\s+/).filter(Boolean);
    const target = norm(it.text);
    $('pr-self').onclick = () => {
      // Unverified: counts as practice with support, never as mastery evidence.
      this.r.attempts = 1; this.r.partial = 0.5; this.r.chosen = 'self-report'; this.r.hint = true;
      this.finish(true, 'Great reading practice! ⭐');
    };
    if (!$('pr-mic')) return;
    $('pr-mic').onclick = () => {
      const SR = window.SpeechRecognition || window.webkitSpeechRecognition;
      let rec;
      try { rec = new SR(); } catch (e) { UI.toast('The microphone is not available'); return; }
      rec.lang = 'en-US'; rec.interimResults = true; rec.maxAlternatives = 1; rec.continuous = false;
      $('pr-mic').textContent = '👂 Listening...'; $('pr-mic').disabled = true;
      let heard = '';
      rec.onresult = (e) => {
        heard = Array.from(e.results).map(r => r[0].transcript).join(' ');
        const got = norm(heard);
        target.forEach((w, i) => { const el = document.querySelector(`[data-w="${i}"]`); if (el && got.includes(w)) el.classList.add('heard'); });
        $('pr-heard').textContent = '“' + heard + '”';
      };
      const end = () => {
        const got = norm(heard);
        const matched = target.filter(w => got.includes(w)).length;
        const ratio = target.length ? matched / target.length : 0;
        this.r.attempts++;
        if (ratio < 0.8 && this.r.attempts === 1 && heard) { this.r.firstTry = false; $('pr-mic').disabled = false; $('pr-mic').textContent = '🎤 Try again'; this.nudge(); return; }
        if (!heard) { $('pr-mic').disabled = false; $('pr-mic').textContent = '🎤 Start reading'; UI.toast('I didn\'t hear anything - try again!'); this.r.attempts--; return; }
        this.r.partial = ratio; this.r.chosen = heard;
        this.finish(ratio >= 0.8, ratio >= 0.8 ? 'Wonderful reading! 📖' : null);
      };
      rec.onend = end; rec.onerror = () => { };
      try { rec.start(); } catch (e) { UI.toast('The microphone is not available'); }
    };
  },

  // ---------- finishing ----------
  finish(ok, msg) {
    const it = this.it;
    this.r.correct = ok; this.r.ms = performance.now() - this.t0;
    if (!this.opts.noRecord) Learn.record(it, this.r);
    ok ? Sound.right() : Sound.wrong();
    const fb = $('pr-feedback');
    if (!fb) return this.done();
    document.querySelectorAll('#pr-hint').forEach(e => e.remove());
    fb.innerHTML = `<p class="affirm">${ok ? esc(msg || pick(['Correct! ✨', 'You got it! 💖', 'Brilliant! 🌟', 'Yes! 👑', 'Super thinking! 🧠'])) : 'Good try! 🌱 Here is how it works:'}</p>
      ${ok ? '' : `<p class="center explain">${esc(it.explain)}</p>`}
      <div class="row-btns"><button class="big-btn purple" id="pr-next">Next ➜</button></div>`;
    $('modal-box').scrollTop = $('modal-box').scrollHeight;
    if (!ok) Voice.speak('Good try! ' + it.explain);
    $('pr-next').onclick = () => this.done();
  },
  done() {
    const cb = this.opts.onDone, r = this.r;
    this.it = null;
    UI.onModalClose = null;
    if (cb) cb(r);
  },
  cancel() {
    if (!this.it) return;
    const cb = this.opts.onDone; this.it = null;
    if (cb) cb(Object.assign({}, this.r, { cancelled: true }));
  },
};

// ---------- hands-on science experiments ----------
const FLOATERS = [['🪨', 'rock', 'sink'], ['🍃', 'leaf', 'float'], ['🪙', 'coin', 'sink'], ['🦆', 'rubber duck', 'float'], ['🍎', 'apple', 'float'], ['🔑', 'key', 'sink'], ['🧽', 'sponge', 'float'], ['🥄', 'spoon', 'sink'], ['🪵', 'wood block', 'float'], ['🔮', 'marble', 'sink']];
const MAGNETIC = [['📎', 'paper clip', 'yes'], ['🔩', 'iron screw', 'yes'], ['🪛', 'screwdriver tip', 'yes'], ['🧷', 'safety pin', 'yes'], ['✏️', 'pencil', 'no'], ['🧸', 'teddy bear', 'no'], ['🍃', 'leaf', 'no'], ['📄', 'paper', 'no'], ['🦆', 'rubber duck', 'no'], ['🧽', 'sponge', 'no']];

function makeExperiment(kind, skillId) {
  const sk = SKILL_BY_ID[skillId];
  const meta = { grade: sk.grade, subject: sk.subject, domain: sk.domain, skill: sk.id, skillName: sk.name, difficulty: Learn.levelFor(sk.id), prereq: sk.prereq, reward: 2, tags: {} };
  const base = { plant: { prompt: 'Plant Lab 🌱', hint: 'Plants need sunlight AND water to grow.', explain: 'Plants grow best with both sun and water.' },
    float: { prompt: 'Sink or Float? 🛁', hint: 'Heavy things for their size usually sink. Light things float.', explain: 'Things that are heavy for their size sink; light, airy things float.' },
    magnet: { prompt: 'Magnet Lab 🧲', hint: 'Magnets pull on some metals like iron and steel.', explain: 'Magnets attract iron and steel, but not wood, paper, plastic or cloth.' } }[kind];
  return Object.assign(meta, base, { type: 'experiment', kind, key: 'exp' + kind + Date.now() });
}

const Experiments = {
  run(it) { this.it = it; this['run_' + it.kind](); },
  frame(title, inner) {
    return `<div class="mg-head"><span>🔬 ${esc(title)}</span><span class="muted">Science experiment</span></div>${Present.opts.frame ? `<div class="frame">${Present.opts.frame}</div>` : ''}${inner}`;
  },
  // Plant three seeds, choose sun & water for each, watch them grow, then explain.
  run_plant() {
    const pots = [{ sun: true, water: true }, { sun: true, water: false }, { sun: false, water: true }];
    const render = () => {
      UI.open(this.frame('Plant Lab', `<p class="mg-prompt">Plant 3 seeds. Give each one sun ☀️ or dark 🌑, and water 💧 or no water 🚫. Then watch them grow!</p>
        <div class="pots">${pots.map((p, i) => `<div class="pot"><div class="plant" id="pl-${i}">🌰</div><div class="soil"></div><b>Pot ${i + 1}</b>
          <button class="mid-btn ${p.sun ? 'on' : ''}" data-sun="${i}">${p.sun ? '☀️ Sun' : '🌑 Dark'}</button>
          <button class="mid-btn ${p.water ? 'on' : ''}" data-water="${i}">${p.water ? '💧 Water' : '🚫 No water'}</button></div>`).join('')}</div>
        <div class="row-btns"><button class="big-btn green" id="pl-go">🌱 Grow for 7 days!</button></div>`), { onClose: () => Present.cancel() });
      Voice.speak('Plant three seeds. Choose sun or dark, and water or no water, for each one. Then watch them grow!');
      document.querySelectorAll('[data-sun]').forEach(b => b.onclick = () => { pots[+b.dataset.sun].sun = !pots[+b.dataset.sun].sun; render(); });
      document.querySelectorAll('[data-water]').forEach(b => b.onclick = () => { pots[+b.dataset.water].water = !pots[+b.dataset.water].water; render(); });
      $('pl-go').onclick = () => {
        const sig = pots.map(p => `${p.sun}${p.water}`);
        if (new Set(sig).size < 2) { UI.toast('🔬 Scientists change things to compare! Make the pots different.'); Voice.speak('Scientists change one thing to compare. Make the pots different!'); return; }
        grow();
      };
    };
    const grow = () => {
      let day = 0;
      document.querySelectorAll('[data-sun],[data-water],#pl-go').forEach(b => b.disabled = true);
      const stages = (p) => (p.sun && p.water ? ['🌱', '🌿', '🪴', '🌻'] : p.sun || p.water ? ['🌱', '🌱', '🥀', '🥀'] : ['🌰', '🌰', '🌰', '🌰']);
      const tick = setInterval(() => {
        day++;
        pots.forEach((p, i) => { const el = $('pl-' + i); if (el) { el.textContent = stages(p)[Math.min(3, Math.floor(day / 2))]; el.style.fontSize = (34 + (p.sun && p.water ? day * 7 : day * 1.5)) + 'px'; } });
        Sound.tap();
        if (day >= 7) { clearInterval(tick); setTimeout(ask, 600); }
      }, 450);
    };
    const ask = () => {
      const best = pots.findIndex(p => p.sun && p.water);
      const results = pots.map((p, i) => `<div class="pot small"><div class="plant" style="font-size:${p.sun && p.water ? 70 : 40}px">${p.sun && p.water ? '🌻' : p.sun || p.water ? '🥀' : '🌰'}</div><b>Pot ${i + 1}</b><span>${p.sun ? '☀️' : '🌑'} ${p.water ? '💧' : '🚫'}</span></div>`).join('');
      if (best < 0) {
        // no pot had both: the observation is that nothing grew well
        const q = { prompt: 'None grew into a flower. What do you think they needed?', choices: shuffle(['Both sun and water', 'More darkness', 'Candy']), answer: 'Both sun and water' };
        return this.question(results, q, true);
      }
      const q1 = { prompt: 'Which pot grew best?', choices: pots.map((_, i) => `Pot ${i + 1}`), answer: `Pot ${best + 1}` };
      this.question(results, q1, false, () => {
        const q2 = { prompt: 'WHY did it grow best?', choices: shuffle(['It had sun AND water', 'It was in the dark', 'It had no water']), answer: 'It had sun AND water', qtype: 'why' };
        this.question(results, q2, true);
      });
    };
    render();
  },
  // Predict, then test: sink or float / magnet or not.
  run_float() { this.predictTest('Sink or Float?', shuffle(FLOATERS).slice(0, 4), ['float', 'sink'], ['🛟 Float', '⬇️ Sink'], '🛁'); },
  run_magnet() { this.predictTest('Magnet Lab', shuffle(MAGNETIC).slice(0, 4), ['yes', 'no'], ['🧲 Sticks', '🙅 Does not'], '🧲'); },
  predictTest(title, objs, vals, labels, icon) {
    const guess = {};
    const render = () => {
      UI.open(this.frame(title, `<p class="mg-prompt">${icon} First PREDICT what will happen to each one. Then test it!</p>
        <div class="predict">${objs.map((o, i) => `<div class="prow"><span class="pemo">${o[0]}</span><b>${esc(o[1])}</b>
          ${vals.map((v, k) => `<button class="mid-btn ${guess[i] === v ? 'on' : ''}" data-g="${i}" data-v="${v}">${labels[k]}</button>`).join('')}</div>`).join('')}</div>
        <div class="row-btns"><button class="big-btn green" id="pt-go">🔬 Test it!</button></div>`), { onClose: () => Present.cancel() });
      document.querySelectorAll('[data-g]').forEach(b => b.onclick = () => { guess[+b.dataset.g] = b.dataset.v; Sound.tap(); render(); });
      $('pt-go').onclick = () => {
        if (Object.keys(guess).length < objs.length) { UI.toast('Make a prediction for every one!'); return; }
        let right = 0;
        const rows = objs.map((o, i) => { const ok = guess[i] === o[2]; if (ok) right++; return `<div class="prow result ${ok ? 'ok' : 'no'}"><span class="pemo ${o[2] === 'sink' ? 'sinks' : o[2] === 'float' ? 'floats' : o[2] === 'yes' ? 'sticks' : ''}">${o[0]}</span><b>${esc(o[1])}</b><span>${labels[vals.indexOf(o[2])]}</span><span>${ok ? '✅ You predicted it!' : '🤔 Surprise!'}</span></div>`; }).join('');
        UI.open(this.frame(title, `<p class="mg-prompt">Results!</p><div class="predict tested">${rows}</div><p class="affirm">${right} of ${objs.length} predictions matched. ${right === objs.length ? 'Amazing scientist!' : 'Surprises are how scientists learn!'}</p>
          <p class="center explain">${esc(this.it.explain)}</p><div class="row-btns"><button class="big-btn purple" id="pt-next">Next ➜</button></div>`), { onClose: () => Present.cancel() });
        Voice.speak(`${right} of ${objs.length} predictions matched! ${this.it.explain}`);
        Present.r.attempts = 1; Present.r.partial = right / objs.length; Present.r.chosen = `${right}/${objs.length}`; Present.r.correct = right / objs.length >= 0.75;
        Present.r.ms = performance.now() - Present.t0;
        if (!Present.opts.noRecord) { Learn.record(this.it, Present.r); Learn.countActivity('experiment'); }
        right / objs.length >= 0.75 ? Sound.right() : Sound.wrong();
        $('pt-next').onclick = () => Present.done();
      };
    };
    render();
    Voice.speak(`${title}! First predict what will happen to each one, then test it!`);
  },
  question(resultsHtml, q, last, next) {
    UI.open(this.frame('Plant Lab', `<div class="pots">${resultsHtml}</div><div class="mg-prompt">${esc(q.prompt)}</div>
      <div class="choices one-col">${q.choices.map((c, k) => `<button class="choice" data-k="${k}">${esc(c)}</button>`).join('')}</div><div id="pr-feedback"></div>`), { onClose: () => Present.cancel() });
    Voice.speak(q.prompt);
    document.querySelectorAll('.choice').forEach(b => b.onclick = () => {
      const ok = q.choices[+b.dataset.k] === q.answer;
      document.querySelectorAll('.choice').forEach(c => { c.disabled = true; if (q.choices[+c.dataset.k] === q.answer) c.classList.add('right'); });
      if (!ok) b.classList.add('wrong');
      // each question in the experiment is its own observation
      const it = Object.assign({}, this.it, { qtype: q.qtype || '', key: this.it.key + q.prompt });
      const r = { correct: ok, firstTry: true, attempts: 1, ms: performance.now() - Present.t0, chosen: q.choices[+b.dataset.k] };
      if (!Present.opts.noRecord) Learn.record(it, r);
      Present.r = Object.assign(Present.r, r);
      ok ? Sound.right() : Sound.wrong();
      $('pr-feedback').innerHTML = `<p class="affirm">${ok ? 'Great observation! 🔬' : 'Look at the pots again 🌱'}</p><p class="center explain">${esc(this.it.explain)}</p><div class="row-btns"><button class="big-btn purple" id="pr-next">Next ➜</button></div>`;
      Voice.speak((ok ? 'Great observation! ' : '') + this.it.explain);
      if (last && !Present.opts.noRecord) Learn.countActivity('experiment');
      $('pr-next').onclick = () => (last || !next ? Present.done() : next());
    });
  },
};
